title: <p align="center"> Geetha Jakka </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/geetha-j-0a3a3223/">LinkedIn</a> |
  <a href="https://github.com/2610geetha">GitHub</a>
  
  <br>   
  Currently I'm working as Senior Manager at GE HealthCare. 
  Want to exlpore MAchine Learning and Artifical Inteligence and 
  started my journey by learning it through Upgrad.
  <br>
  </p>
